services:
  upstream:
    container_name: upstream
    image: "nginx:alpine"
    volumes:
      - ./upstream/nginx.conf:/etc/nginx/nginx.conf
      - ./upstream/html:/usr/share/nginx/html

  proxy:
    container_name: proxy
    image: "nginx:1.24.0-alpine"
    ports:
      - "80:80"
    entrypoint:
      - nginx-debug 
      - -g 
      - "daemon off;"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
